/*
 * This code has been generated by the Rebel: a code generator for modern Java.
 *
 * Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
 */
package com.cda.contenu_seance.model;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import javax.persistence.*;
import java.util.List;

@Entity
@Getter
@Setter
@NoArgsConstructor

public class Competence {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    private String nom;
    private int numOdre;
    @ManyToOne
    private Activite activite;
    @OneToMany(mappedBy = "competence")
    List<SavoirFaire> savoirFaires;

    //TODO faire test pour cas particulier (mettre a l'epuer l'algo)
    public int calSumHeurCompetence() {

        List<SavoirFaire> savoirFaireList = this.getSavoirFaires();
        for (SavoirFaire unSkill : savoirFaireList) {
            List<Seance> skillsSeance = unSkill.getSeances();

            if (!skillsSeance.isEmpty()) {
                return skillsSeance.stream().mapToInt(Seance::getDurer).sum();
            }

        }
        return 0;

    }












}