/*
* This code has been generated by the Rebel: a code generator for modern Java.
*
* Drop us a line or two at feedback@archetypesoftware.com: we would love to hear from you!
*/
package com.cda.contenu_seance.model;

import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.lang.Nullable;

import javax.persistence.*;
import java.time.LocalDate;
import java.util.List;


@Entity
@Getter
@Setter
@NoArgsConstructor
public class Seance {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @DateTimeFormat(pattern = "yyyy-MM-dd")
//    @Temporal(TemporalType.DATE)
    private LocalDate dateDuJour;

    private int durer;
    private String supportUse;
    private String deroulement;
    private String objectifPeda;
    private String methodeEnvisagee;
    private String evaluation;

    @Nullable
    @ManyToOne(fetch = FetchType.LAZY)
    private Formateur formateur;

    @Nullable
    @ManyToOne
    private Session session;

    @Nullable
    @ManyToMany
    private List<SavoirFaire> savoirFaires;


    public Seance(String supportUse, String deroulement, String objectifPeda, String methodeEnvisagee, String evaluation) {
        this.supportUse = supportUse;
        this.deroulement = deroulement;
        this.objectifPeda = objectifPeda;
        this.methodeEnvisagee = methodeEnvisagee;
        this.evaluation = evaluation;
    }

    /**
     * Vrai Si supportUse ou deroulement ou objectifPeda ou methodeEnvisagee ou evaluation sont vide
     * true if supportUse or deroulement or objectifPeda or methodeEnvisagee or evaluation is empty
     * @return boolean
     */
    @Nullable
    public boolean getStringAttIsEmpty() {

        return this.supportUse.isEmpty()
                || this.deroulement.isEmpty()
                || this.objectifPeda.isEmpty()
                || this.methodeEnvisagee.isEmpty();

    }
}